### ISSUE TITLE
Incorrect response with double letters

### ISSUE THREAD

**Issue by zeebo** [ajeetdsouza/clidle#1]
If the hidden word has only a single copy of a letter (say `D` in `DIETS`), and you guess a word with two of that letter (say, `BUDDY`), then it will highlight both as present in the word. Wordle does not work this way. It would only highlight the first, or correct, one.

<details>
<summary>Spoiler for today's wordle showing the wordle behavior</summary>
<img src="https://i.imgur.com/cq5vOZ4.png" />
</details>

Thanks for the neat project!

**Comment by ajeetdsouza** [comment]
Hey, I just fixed this :)

https://github.com/ajeetdsouza/clidle/commit/d3ceb5baaeba7f20f2e67f94d5d4f0951125b4a5
